export const MAP_CREATE_REQUEST = 'MAP_CREATE_REQUEST'
export const MAP_CREATE_SUCCESS = 'MAP_CREATE_SUCCESS'
export const MAP_CREATE_FAIL = 'MAP_CREATE_FAIL'

export const MAP_CLEAR_REQUEST = 'MAP_CLEAR_REQUEST'
export const MAP_CLEAR_SUCCESS = 'MAP_CLEAR_SUCCESS'
export const MAP_CLEAR_FAIL = 'MAP_CLEAR_FAIL'