export const GET_SENSORS_REQUEST = 'GET_SENSORS_REQUEST'
export const GET_SENSORS_SUCCESS = 'GET_SENSORS_SUCCESS'
export const GET_SENSORS_FAIL = 'GET_SENSORS_FAIL'

export const ADD_SENSOR_TO_MAP_REQUEST = 'ADD_SENSOR_TO_MAP_REQUEST'
export const ADD_SENSOR_TO_MAP_SUCCESS = 'ADD_SENSOR_TO_MAP_SUCCESS'
export const ADD_SENSOR_TO_MAP_FAIL = 'ADD_SENSOR_TO_MAP_FAIL'